# title:            Zhiyuan Ma, Poetically Dwell on the Earth
title:            Zhiyuan Ma's Place
description:      不弹吉他的诗人不是好天文学家
url:              https://jerry-ma.github.io # Site url, without a slash at the end.
signoff:          Z. Ma # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.

links:
  - name:         About Me
    url:          /about
  - name:         CV
    url:          /research/cv.pdf#zoom=100
    newtab:       true
  - name:         Research
    url:          /research
  - name:         诗们
    url:          /poem

highlighter:      rouge
permalink:        pretty
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
